### ISSUE TITLE
[recurring] Become a tresinformal team member

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/drakkar#1]
Put your GitHub username here, or ask [a `tresinformal` member](https://github.com/orgs/tresinformal/people) to invite you.

As always, assign yourself when doing this Issue, unassign upon completion.

As this Issue is 'Recurring', this means that:

 * If you want to do this Issue and it is closed: re-open it
 * If there are no assignees left: close it

**Comment by swom** [comment]
Hello, here is Stefano. My GitHub name is swom and my linked email address is cicciacco@gmail.com

**Comment by richelbilderbeek** [comment]
@swom: added you to the tresinformal team, check your inbox for the invite :+1:

**Comment by richelbilderbeek** [comment]
Members:

 * [x] Pedro
 * [ ] Josh: sent invite
 * [x] Stefano
 * [ ] Apu: sent invite
 * [ ] Boris: GitHub username unknown, see #9 
 * [ ] Xiaoyan: sent invite
 * [ ] Marina: sent invite

**Comment by boman0815** [comment]
hey im here (boris)

**Comment by marinapapa** [comment]
Are still getting new members or shall this close?

**Comment by richelbilderbeek** [comment]
* @marinapapa: good suggestion to close indeed. 
 * @Neves-P: I'll speak with @giappo tomorrow, let's see if I can get him in :+1:

Closing!

**Comment by TheoPannetier** [comment]
Hi all, I'm Theo, @TheoPannetier on GitHub I'd love to join the team, starting next Wednesday 👍

**Comment by pohaha** [comment]
hello, i don't really know if this thing is still going, but if i can learn anything related to development i would shureley like to join! This is my first time trying to participate in some open source project - so please feel free to tell me if i'm doing anything wrong

**Comment by richelbilderbeek** [comment]
Hi @pohaha, you are definitely welcome to join the team! We meet on Wednesdays 17:00-19:00 Amsterdam time, so I hope you are lucky with the timezones :-). If you'd like, I am open to a videochat on Discord ( richelbilderbeek#9002 ) or any platform. See you this Wednesday? Yes == fun!

**Comment by pohaha** [comment]
yes i've added you in discord. i would really appreciate some sort of introduction

> Hi @pohaha, you are definitely welcome to join the team! We meet on Wednesdays 17:00-19:00 Amsterdam time, so I guess that is 18:00-20:00 in Saint-Petersburg :-). If you'd like, I am open to a videochat on Discord ( richelbilderbeek#9002 ) or any platform. See you this Wednesday? Yes == fun!

**Comment by TheoPannetier** [comment]
> If there are no assignees left: close it

No assignees left, let's close this issue until a new member joins 👍

**Comment by ollyturner** [comment]
👍

**Comment by kausmees** [comment]
Hi!

I would like to join, please add me. Thanks!

**Comment by TheoPannetier** [comment]
Done !

**Comment by TheoPannetier** [comment]
Done!

**Comment by kausmees** [comment]
Thanks, closing it again.

**Comment by mrcoolepicman** [comment]
Done. :)))))))))))))))))))))))))))))

**Comment by MahshidGhods** [comment]
done

**Comment by maedas** [comment]
Done, memberd and hydrated like a real homie
