### ISSUE TITLE
implement linear algebra - like arithmetic?[POLL]

### ISSUE THREAD

**Issue by pohaha** [tresinformal/drakkar#332]
Should we or should we not implement linear-algebra like arithmetic?
that includes unit vectors of movement direction, speed represented as a volume of said vector, math would have to change  correspondingly. 
Like if agree dislike if disagree

**Comment by swom** [comment]
ahhh math! I do not understand!

**Comment by richelbilderbeek** [comment]
@pohaha you want me to poll this next Wednesday? If yes, I will give you max five minutes to explain this to the team.

**Comment by TheoPannetier** [comment]
@richelbilderbeek do we still want to discuss this some day? Or should we close the issue?

**Comment by TheoPannetier** [comment]
This hasn't been discussed in a while, I'll take the initiative to close it :)
