### ISSUE TITLE
Transition from x and y to coordinate

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/drakkar#346]
Hi @swom and @pohaha, 

I though to write down the transition from:

```c++
class my_class
{
  double get_x() const noexcept;
  double get_y() const noexcept;
};
```

to

```c++
class my_class
{
  const coordinate& get_coordinate() const noexcept;
};
```

Phases are:

 1. Reduce dependency on `my_class::get_x` and `my_class::get_y`
 2. Replace the back-end, i.e. write `my_class::get_coordinate`

To be more precise:

 * Write free functions `double get_x(const my_class&)` and `double get_y(const my_class&)`: easy to write tests for and juniors can do this :-)
 * Replace calls to `my_class::get_x` and `my_class::get_y` by calls to `double get_x(const my_class&)` and `double get_y(const my_class&)`: this is something that happens in the back, but a junior can do this as well
 * Make `my_class` use a `coordinate`, let `double get_x(const my_class&)` and `double get_y(const my_class&)` now call `my_class::get_coordinate`
 * Keep the logistic functions `double get_x(const my_class&)` and `double get_y(const my_class&)` for now, phase these out later if that is really worth it (I predict: it will never be :-) )

You probably want to do this one a per-class basis, but multiple classes worked on by different people would also work.

I hope this helps :-)

**Comment by TheoPannetier** [comment]
Just fixing the spelling of coordinate to avoid that someone writes "coordinat" in the code later 🤓

**Comment by TheoPannetier** [comment]
I believe this is complete by now!
