### ISSUE TITLE
it is possible to get the position of a player logistic functions

### ISSUE THREAD

**Issue by swom** [tresinformal/drakkar#401]
Depends on

- [x] #324

The following test should pass in player.cpp:

```c++
//#define FIX_ISSUE_401
#ifdef FIX_ISSUE_401
    {
        auto x = 1.23456;
        auto  y = 123456.789;
        coordinate c{x, y};
        player p{c};
        assert(get_position(p) == c);
    }
#endif
```

**Comment by TheoPannetier** [comment]
Hey @swom, do you think this issue could be made available for Wednesday? We have a bunch of new people joining, and this and #402 look like good material for a `first` issue 😉

**Comment by TheoPannetier** [comment]
Done :)

**Comment by TheoPannetier** [comment]
Done :)
