### ISSUE TITLE
[recurring] Make a branch for yourself via the GitHub web interface

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/drakkar#47]
It's easy if you know where to click:

![there](https://user-images.githubusercontent.com/2098230/67526085-53ae7880-f6b4-11e9-9d4e-73995a7ed9b8.png)

We follow the convention that your branch will have your name in lowercase, e.g. `richel`.

When done, unassign yourself here and assign yourself to #48 :+1:

As always, assign yourself when doing this Issue, unassign upon completion.

As this Issue is 'Recurring', this means that:

 * If you want to do this Issue and it is closed: re-open it
 * If there are no assignees left: close it

**Comment by mrcoolepicman** [comment]
Done.

**Comment by MahshidGhods** [comment]
Done
