### ISSUE TITLE
Excess output after termination of the game

### ISSUE THREAD

**Issue by EvoLandEco** [tresinformal/drakkar#526]
```
14:12:20: Starting C:\Users\tianj\Documents\build-game-Desktop_Qt_5_12_2_MinGW_64_bit-Debug\debug\game.exe...
gezelligColor(255, 255, 255)active14:12:25: C:\Users\tianj\Documents\build-game-Desktop_Qt_5_12_2_MinGW_64_bit-Debug\debug\game.exe exited with code 0
```
`gezelligColor(255, 255, 255)active` is printed after termination of the game. Looks like it is introduced by some of the recent commits.

**Comment by EvoLandEco** [comment]
Related to #520 , color and player state were passed to `std::cout` in the tests, after the implementation of overloading `<<` operator

**Comment by TheoPannetier** [comment]
I believe this has been fixed, but do re-open if I'm mistaken!
