### ISSUE TITLE
A player's score cannot be negative

### ISSUE THREAD

**Issue by TheoPannetier** [tresinformal/drakkar#591]

**Comment by EvoLandEco** [comment]
Some games do allow for negative scores, especially in PvP mode. Let's say if you constantly got killed/eaten, or ran into traps, fell into holes, it might make more sense to have a negative score if there is no point left to be deducted, just consider it a debt?

**Comment by TheoPannetier** [comment]
Closing; for now this is no longer an issue as the score is conflated with player size, which cannot be negativeby construction
