### ISSUE TITLE
A player that is out cannot interact with anything

### ISSUE THREAD

**Issue by TheoPannetier** [tresinformal/drakkar#607]
Depends on:

- [ ] #621 
- [ ] #622 
- [ ] #623 
- [ ] #624 
- [ ] #625

Once all of the above issues are completed, you can consider this one done and close it too :)

**Comment by TheoPannetier** [comment]
Closing; we no longer need any of the above for the MVG except for #625, such that this issue would be a duplicate of the latter.

**Comment by EvoLandEco** [comment]
I implemented this concept in another way: a player that is out becomes a "ghost" thus it cannot grow/shrink, and cannot let other players grow/shrink. More complicated interactions should be discussed later.

**Comment by EvoLandEco** [comment]
No I got it wrong, out is a different thing, it has nothing to do with #535

**Comment by TheoPannetier** [comment]
Yes, here 'out' happens after you've been eliminated, e.g. by shrinking below a threshold size 🙂
