### ISSUE TITLE
Define minimal viable game

### ISSUE THREAD

**Issue by ollyturner** [tresinformal/drakkar#633]
We need to decide which steps we still need to take before we get to the minimal viable game.
This doesn't only mean adding things, but also temporarily remove things.

**Comment by sebmader** [comment]
Higher level: what do you need for a minimal viable game?

- Winning condition
- Menu: start the game

**Comment by sebmader** [comment]
Lower level:

Winning condition:

- Timer runs out
- Whoever is larger, wins

**Comment by sebmader** [comment]
How to get larger?

- run into another player and win, i.e. eat them

How to win?
we have two options for basic winning dynamic:
1. colour
2. size
Choose one.

points for colour:
- + we already have it
- + is fun
- - "broken" dynamics

points for size:
- - "broken" dynamics

**==> COLOUR**

**Comment by EvoLandEco** [comment]
> Menu Scoreboard Remove rockets and stun rockets Remove Food Remove Colour Functionality (you can keep the colour as a design) Need to be able to win and lose (who is bigger when they collide) Size If players are same size a winner is randomly generated

Could it be a due game if all the players are of the same size or the same socre?

**Comment by sebmader** [comment]
> Menu Scoreboard Remove rockets and stun rockets Remove Food Remove Colour Functionality (you can keep the colour as a design) Need to be able to win and lose (who is bigger when they collide) Size If players are same size a winner is randomly generated

@ollyturner @TheoPannetier 
We still need a conclusion on what we need for our minimal viable game.
I propose (from the quoted list):

Menu
-Scoreboard- (strikethrough)
Remove rockets and stun rockets
Remove Food
Colour Functionality as means to win a confrontation
Winning condition: who's bigger at the end of time
-If players are same size a winner is randomly generated-

**Comment by TheoPannetier** [comment]
Then it looks like we have enough to write a clear Minimal Viable Game plan (I volunteer to do this)!

**Comment by TheoPannetier** [comment]
There is however one issue we need to address: @EvoLandEco has been working on implementing a scoreboard to track points, but AFAICS in the plan above and its winning conditions we have no need to keep track of a score at all?

The winner is simply whoever is largest when the timer reaches zero, so "score"  is simply the size attribute of the player.

@EvoLandEco would it be ok for you to ditch the scoreboard for now?

**Comment by EvoLandEco** [comment]
> There is however one issue we need to address: @EvoLandEco has been working on implementing a scoreboard to track points, but AFAICS in the plan above and its winning conditions we have no need to keep track of a score at all?
> 
> The winner is simply whoever is largest when the timer reaches zero, so "score" is simply the size attribute of the player.
> 
> @EvoLandEco would it be ok for you to ditch the scoreboard for now?

In the concept of a MVG there is no need for a scoring board. As the scoring board has currently no interaction with any other part, we could just stop implementing it, or the same like the enemy class we could also remove the file temporarily. We could resurrect it later

**Comment by TheoPannetier** [comment]
Great, then this point is solved :)
