### ISSUE TITLE
Remove enemy?

### ISSUE THREAD

**Issue by TheoPannetier** [tresinformal/drakkar#661]
The game currently contains a class `enemy` that creates an object in the game.
As of now, this enemy only consists in a position.

As far as I'm aware of, a Minimum Viable Game doesn't contain any enemy, and in fact, I don't remember hearing any plan from anyone involved in design about including something like an enemy.

Unless someone tells otherwise, I think we should ban enemies and ruthlessly remove any mention of them in the code.

**Comment by TheoPannetier** [comment]
@EvoLandEco @ollyturner @sebmader what's your opinion on this?

**Comment by EvoLandEco** [comment]
@TheoPannetier I actually don't know what's enemy about, I haven't heard any plan about it either. For the minimal viable game I agree we could just remove it's existence and maybe archive the code somewhere else.

**Comment by TheoPannetier** [comment]
@EvoLandEco the great thing with version control is that we don't need to archive code: it's already done in the version history 😁
