### ISSUE TITLE
Shelters were not completely removed from the code

### ISSUE THREAD

**Issue by EvoLandEco** [tresinformal/drakkar#685]
@TheoPannetier when we are trying to remove food from the code, we see a lot of mentions of shelters in the code, could it be that you haven't opened a pull request yet?

**Comment by TheoPannetier** [comment]
Yup, correct! You can see this in the [Network Graph](https://github.com/tresinformal/drakkar/network).
`minimal` is one commit ahead (and some more behind) `develop`, and that commit just happens to be... the one where I removed shelters! https://github.com/tresinformal/drakkar/commit/41a31d4528dfd399b87897c2bbb73d59021ebfa4
I'll make a PR soon :)
