### ISSUE TITLE
Rename `game_view::draw_player_coords` to `game_view::draw_player_info`

### ISSUE THREAD

**Issue by EvoLandEco** [tresinformal/drakkar#690]
This function currently does more than its name indicates, I plan to make this function show more info (for example player size) on the fourth panel, let's rename it to `game_view::draw_player_info`

**Comment by TheoPannetier** [comment]
I don't think such simple changes as refactoring require opening an issue for it, unless you plan to do it later or have someone else work on it later ;)

**Comment by EvoLandEco** [comment]
@TheoPannetier Maybe as a reference in case someone couldn't find these functions? 😋 Anyway it's done, closed by #693
