### ISSUE TITLE
Change default branch to `develop`

### ISSUE THREAD

**Issue by EvoLandEco** [tresinformal/drakkar#694]
Do you think it would be a good idea to change the default branch from `master` to `develop`? IMO,

- this can avoid unintended PRs and commits to the `master`
- this saves us a few seconds every time we create a PR
- this will help us to enjoy the advantage of closing keywords

**Comment by richelbilderbeek** [comment]
We'll vote on it today :-)

**Comment by TheoPannetier** [comment]
I vote against, for the same reasons as Richel.
The default branch is the one users see and download the software from; there should be absolutely no risk of it being broken and it should not have experimental features on.

But I agree with your motivations, it is unfortunate that Github doesn't suggest merging to develop by default despite this being the model used by the vast majority of projects, as far as I know.

**Comment by richelbilderbeek** [comment]
@EvoLandEco I conclude that this Issue has been dealt with. We've nicely discussed the pros and cons, voted democratically and decided that `master` remains the default branch. I hope you agree with the process and a re-vote in the future can be requested.

For now, let's close this Issue :-)
