### ISSUE TITLE
Colour and winner: intended behaviour or not?

### ISSUE THREAD

**Issue by EvoLandEco** [tresinformal/drakkar#698]
**Blue > Red > Green**

This is a rule in the code to decide the winner when two players collide. Is it an intended behaviour?

**Comment by richelbilderbeek** [comment]
Yes, this was the earlier intended behavior. AFAICS, we removed these paper-rock-scissors dynamics for now.

**Comment by TheoPannetier** [comment]
Yes, Rock-Paper-Scissor dynamics is the central part of the gameplay; 
AFAICS @richelbilderbeek it is still the case (and we want to keep it!)
