### ISSUE TITLE
Use std::abs instead of abs and fabs

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/drakkar#734]
Currently, the code contains calls to `abs` and `fabs`, to get the absolute value of a number. These functions, however, are not C++ functions: these are C functions.  [CPL.1: Prefer C++ to C](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rcpl-C). In C++, there is `std::abs` to get the absolute value of any type of number.

Look for `abs` and `fabs` and replace these both by `std::abs`

**Comment by Luxwor** [comment]
Fixed
